# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - windows
julia:
<<<<<<< HEAD
  - 1.2
=======
  - nightly
  - 1
>>>>>>> 963980a7e2af22639d7530a18eafe4b2dddaac28
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
addons:
      apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
install:
  - sudo pip install matplotlib

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.add("ReverseDiffSparse")'
  - julia -e 'Pkg.checkout("ReverseDiffSparse")'
<<<<<<< HEAD
  # - julia -e 'Pkg.add("KNITRO")'
  # - julia -e 'Pkg.pin("KNITRO",v"0.4")'
=======
>>>>>>> 963980a7e2af22639d7530a18eafe4b2dddaac28
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("NLOptControl")'
#  - julia -e 'run(`lualatex -v`)'
  - julia -e 'Pkg.checkout("NLOptControl")'
  - julia -e 'Pkg.add("Documenter");'
  - julia -e 'cd(Pkg.dir("NLOptControl"));ENV["DOCUMENTER_DEBUG"]=true; include(joinpath("docs", "make.jl"))'
