# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
sudo: required
os:
  - linux
  - windows
julia:
  - nightly
  - 1
matrix:
    allow_failures:
        - julia: nightly
notifications:
  email: false
addons:
      apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter");'
  - julia -e 'using Pkg; ENV["DOCUMENTER_DEBUG"]=true; import NLOptControl; cd(joinpath(dirname(pathof(NLOptControl)), "..")); ; include(joinpath("docs", "make.jl"))'
